### ISSUE TITLE
Error running app with cordova-android@7.1.0

### ISSUE THREAD

**Issue by kduvnjak** [usabilla/usabilla-u4a-cordova#8]
I'm trying to integrate plugin into my Ionic project running on cordova-android@7.1.0, Android Gradle plugin version 3.1.4 and Gradle version 4.4, first error that I get is 

> The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Update Build Tools version and sync project
Open File

this is resolved by deleting this snippet from usabilla.gradle

`cdvBuildToolsVersion = "26.0.2"
cdvCompileSdkVersion = 26
cdvMinSdkVersion = 16`

after that when I try to run the application I get error

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: hr.test.testapp, PID: 8957
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{hr.test.testapp/com.usabilla.MainActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6776)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
                   Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                      at android.view.ViewGroup.addViewInner(ViewGroup.java:4659)
                      at android.view.ViewGroup.addView(ViewGroup.java:4500)
                      at android.view.ViewGroup.addView(ViewGroup.java:4440)
                      at android.view.ViewGroup.addView(ViewGroup.java:4413)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1007)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                      at android.app.BackStackRecord.run(BackStackRecord.java:815)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1582)
                      at android.app.FragmentController.execPendingActions(FragmentController.java:372)
                      at android.app.Activity.performStart(Activity.java:6971)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045) 
                      at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6776) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386) `

which I resolve by replacing android plugin dependency 

`    <dependency id="cordova-android-fragments"/>
`
with 

`    <dependency id="cordova-plugin-android-fragmentactivity"/>
` 

which is a successor plugin of the plugin currently used

**Comment by kioli** [comment]
Hi @kduvnjak sorry for the delay.
I hope the new version fixes the bug you mentioned :)
